/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package org.apache.hadoop.io.serializer.avro;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class AvroRecord extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"AvroRecord\",\"namespace\":\"org.apache.hadoop.io.serializer.avro\",\"fields\":[{\"name\":\"intField\",\"type\":\"int\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public int intField;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public AvroRecord() {}

  /**
   * All-args constructor.
   */
  public AvroRecord(Integer intField) {
    this.intField = intField;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public Object get(int field$) {
    switch (field$) {
    case 0: return intField;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, Object value$) {
    switch (field$) {
    case 0: intField = (Integer)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'intField' field.
   */
  public Integer getIntField() {
    return intField;
  }

  /**
   * Sets the value of the 'intField' field.
   * @param value the value to set.
   */
  public void setIntField(Integer value) {
    this.intField = value;
  }

  /** Creates a new AvroRecord RecordBuilder */
  public static Builder newBuilder() {
    return new Builder();
  }
  
  /** Creates a new AvroRecord RecordBuilder by copying an existing Builder */
  public static Builder newBuilder(Builder other) {
    return new Builder(other);
  }
  
  /** Creates a new AvroRecord RecordBuilder by copying an existing AvroRecord instance */
  public static Builder newBuilder(AvroRecord other) {
    return new Builder(other);
  }
  
  /**
   * RecordBuilder for AvroRecord instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<AvroRecord>
    implements org.apache.avro.data.RecordBuilder<AvroRecord> {

    private int intField;

    /** Creates a new Builder */
    private Builder() {
      super(AvroRecord.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.intField)) {
        this.intField = data().deepCopy(fields()[0].schema(), other.intField);
        fieldSetFlags()[0] = true;
      }
    }
    
    /** Creates a Builder by copying an existing AvroRecord instance */
    private Builder(AvroRecord other) {
            super(AvroRecord.SCHEMA$);
      if (isValidValue(fields()[0], other.intField)) {
        this.intField = data().deepCopy(fields()[0].schema(), other.intField);
        fieldSetFlags()[0] = true;
      }
    }

    /** Gets the value of the 'intField' field */
    public Integer getIntField() {
      return intField;
    }
    
    /** Sets the value of the 'intField' field */
    public Builder setIntField(int value) {
      validate(fields()[0], value);
      this.intField = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'intField' field has been set */
    public boolean hasIntField() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'intField' field */
    public Builder clearIntField() {
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    public AvroRecord build() {
      try {
        AvroRecord record = new AvroRecord();
        record.intField = fieldSetFlags()[0] ? this.intField : (Integer) defaultValue(fields()[0]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
